- name: Setup System module
  template:
    src: system.yml.j2
    dest: /etc/filebeat/modules.d/system.yml
    owner: root
    group: root
    mode: 0750
  notify: restart filebeat

- name: Turn on System module
  file:
    path: /etc/filebeat/modules.d/system.yml.disabled
    state: absent