- name: Setup MySQL module
  template:
    src: mysql.yml.j2
    dest: /etc/filebeat/modules.d/mysql.yml
    owner: root
    group: root
    mode: 0750
  notify: restart filebeat

- name: Turn on MySQL module
  file:
    path: /etc/filebeat/modules.d/mysql.yml.disabled
    state: absent