---
# tasks file for logstash

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  static: no 

- name: Install Logstash package
  package:
    name: logstash
    state: present

- name: Configure logstash