galaxy_info:
  author: David Marthy
  description: role for installing winlogbeat
  company:

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.2
  platforms:
  - name: Windows
    versions:
    - all
  galaxy_tags: []

dependencies: []