image: marthydavid/ansible_lint:centos7
test-CentOS:
  stage: test
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

image: marthydavid/ansible_lint:alpine
test-Alpine:
  stage: test
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

image: marthydavid/ansible_lint:ubuntu16
test-Ubuntu16:
  stage: test
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

image: marthydavid/ansible_lint:debian9
test-Debian9:
  stage: test
  script:
    - printf '[defaults]\nroles_path=./roles/' >ansible.cfg
    - ansible-lint tests/test.yml
    - ansible-playbook -i tests/inventory tests/test.yml --syntax-check