- name: Setup MySQL module
  template:
    src: mysql.yml.j2
    dest: /etc/metricbeat/modules.d/mysql.yml
    owner: root
    group: root
    mode: 0750
  notify: restart metricbeat

- name: Trun on PostgreSQL module
  file:
    path: /etc/metricbeat/modules.d/mysql.yml.disabled
    state: absent