- name: Setup PostgreSQL module
  template:
    src: postgresql.yml.j2
    dest: /etc/metricbeat/modules.d/postgresql.yml
    owner: root
    group: root
    mode: 0750
  notify: restart metricbeat

- name: Turn on PostgreSQL module
  file:
    path: /etc/metricbeat/modules.d/postgresql.yml.disabled
    state: absent